"""init

Revision ID: 2d0ee9dd25d0
Revises: 
Create Date: 2024-04-07 13:52:36.280629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d0ee9dd25d0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airdrop',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('signer', sa.String(length=64), nullable=True),
    sa.Column('signature', sa.String(length=5120), nullable=True),
    sa.Column('extrinsic_hash', sa.String(length=66), nullable=True),
    sa.Column('fail_reason', sa.String(length=66), nullable=True),
    sa.Column('creat_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('update_time', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account', name='unique_account'),
    sa.UniqueConstraint('extrinsic_hash', name='unique_hash')
    )
    op.create_index(op.f('ix_airdrop_account'), 'airdrop', ['account'], unique=False)
    op.create_index(op.f('ix_airdrop_extrinsic_hash'), 'airdrop', ['extrinsic_hash'], unique=False)
    op.create_index(op.f('ix_airdrop_id'), 'airdrop', ['id'], unique=False)
    op.create_index(op.f('ix_airdrop_signer'), 'airdrop', ['signer'], unique=False)
    op.create_index(op.f('ix_airdrop_status'), 'airdrop', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_airdrop_status'), table_name='airdrop')
    op.drop_index(op.f('ix_airdrop_signer'), table_name='airdrop')
    op.drop_index(op.f('ix_airdrop_id'), table_name='airdrop')
    op.drop_index(op.f('ix_airdrop_extrinsic_hash'), table_name='airdrop')
    op.drop_index(op.f('ix_airdrop_account'), table_name='airdrop')
    op.drop_table('airdrop')
    # ### end Alembic commands ###
