"""添加已经空投的表

Revision ID: 96515556a49a
Revises: fd0ea303a317
Create Date: 2024-04-11 17:47:43.937215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96515556a49a'
down_revision: Union[str, None] = 'fd0ea303a317'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('already_airdrop',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=64, scale=18), nullable=False),
    sa.Column('extrinsic_hash', sa.String(length=66), nullable=True),
    sa.Column('creat_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('update_time', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account', name='unique_account')
    )
    op.create_index(op.f('ix_already_airdrop_account'), 'already_airdrop', ['account'], unique=False)
    op.create_index(op.f('ix_already_airdrop_extrinsic_hash'), 'already_airdrop', ['extrinsic_hash'], unique=False)
    op.create_index(op.f('ix_already_airdrop_id'), 'already_airdrop', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_already_airdrop_id'), table_name='already_airdrop')
    op.drop_index(op.f('ix_already_airdrop_extrinsic_hash'), table_name='already_airdrop')
    op.drop_index(op.f('ix_already_airdrop_account'), table_name='already_airdrop')
    op.drop_table('already_airdrop')
    # ### end Alembic commands ###
