"""修改amount字段

Revision ID: f59206ba49f4
Revises: 2d0ee9dd25d0
Create Date: 2024-04-07 14:23:56.397908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f59206ba49f4'
down_revision: Union[str, None] = '2d0ee9dd25d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('airdrop', 'amount',
               existing_type=mysql.INTEGER(),
               type_=sa.DECIMAL(precision=64, scale=18),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('airdrop', 'amount',
               existing_type=sa.DECIMAL(precision=64, scale=18),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
