"""hashbuweiyi

Revision ID: fd0ea303a317
Revises: f59206ba49f4
Create Date: 2024-04-09 12:54:42.303787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd0ea303a317'
down_revision: Union[str, None] = 'f59206ba49f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('unique_hash', table_name='airdrop')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('unique_hash', 'airdrop', ['extrinsic_hash'], unique=True)
    # ### end Alembic commands ###
